Mapping temp
RPM-lab-UMN/spot_ros pull request #2
Opened 2023-06-26 18:24 UTC by Rhettoric74

This branch adds functions for recording GraphNav maps, as well as refactoring the functions for navigating GraphNav maps so that they fit better within the wrapper. Two new example scripts are added to demonstrate how to use the GraphNav features of the wrapper.

2023-06-29 17:12 UTC, baldeeb reviewed
First off, great work! clean code so far. I am yet to go through everything but I added comments that will require some work to address. Ping me when you are done or if you would like to discuss some of the comments.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +        self.spot = SpotWrapper('admin',
Instead of hardcoding the user credentials, use environment variables that are set by the setup script.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/mapping_example.py
> +        self.spot = SpotWrapper('admin',
Instead of hardcoding the user credentials, use environment variables that are set by the setup script.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/mapping_example.py
> +        # waypoint arguments must be passed in as a list.
The function _set_initial_localiation_waypoint seems to expect a single waypoint. the reason it is taking multiple is due to args being indexed twice in the function. Update the unction so that it can take in a single point.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/mapping_example.py
> +        # waypoint arguments must be passed in as a list.
To ensure backward compatibility make sure to check if the first argument is a list and only then select its first waypoint.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/mapping_example.py
> +        self.spot.navigate_to(download_path + "/downloaded_graph", waypoints[0], False, waypoints[-1])
why does this function need a path? Is there a functional reason why it downloads the graph before proceeding? If not, let's either make this an optional argument or remove it completely. If other functions this as is, what are those functions and is it easy to revamp them?

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/mapping_example.py
> +        time.sleep(2)
remove redundant or unused code.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +    def __upload_recording_test__(self, uploadPath): #Test Script for testing an upload of a pre-recorded graph
I have not seen the double underscore as a suffix. Is it common? if not let's stick to a single underscore as a prefix for protected methods.

Also, the comment string is redundant and not the proper docstring notation. If you want to document the function use ''' documentation ''' inside the function and at the top of it.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +        self.spot._set_initial_localization_waypoint(["cb"])
why is that point hardcoded? is there a way to get the first waypoint from the loaded graph instead?

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +        self.spot._navigate_to(["cb"])
same comment as above.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +        self.spot._navigate_route(["sd","db"])
cool function! Similarly, do we need to hardcode those points?

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +    def __obtain_recording_test__(self): #Test script for recording a path and downloading the recording to local machine
Same comment as above about naming and doc-strings.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +    def __obtain_recording_test__(self): #Test script for recording a path and downloading the recording to local machine
at a second glance, I can't see where this function is used. If it is not needed, delete it.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +    #########################################################################################
Please delete unused code.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +    #########################################################################################
If you want to retain this for later use or reference, feel free to put it on its own branch. Make the branck name: achive/name .

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/src/spot_driver/spot_wrapper.py
> +# Additional import statements for recording
please remove the comments.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/src/spot_driver/spot_wrapper.py
> +#################### Added code ######################
Similarly, remove the comment. Your code is now part of the core code and does not need to be labeled or distinguished.

2023-06-29 17:12 UTC, baldeeb commented on spot_driver/src/spot_driver/spot_wrapper.py
> +    ############################################################################
This set of functions seems like it could reside in a separate class. Maybe GraphNavWrapper. That class could reside in a file in utils. It only needs to be provided with the 3 clients it uses. 
What do you think? If this makes sense, let's move the functions, if not, I would like to know why. This code is already bloated so we should try not to add to it and relieve it from some functions instead.

2023-06-29 19:10 UTC, Rhettoric74 commented on spot_driver/scripts/examples/recording_example.py
> +        self.spot = SpotWrapper('admin',
We hardcoded credentials because they are hardcoded in other example scripts that we didn't make (task_wrapper_example and hand_pose example). Should we also change those examples to use environment variables? I also have been having trouble finding documentation/an example of how to use those environment variables, so please direct me to where if you know where to find that.

2023-06-29 19:27 UTC, Rhettoric74 commented on spot_driver/scripts/examples/mapping_example.py
> +        self.spot.navigate_to(download_path + "/downloaded_graph", waypoints[0], False, waypoints[-1])
There is no need to take an upload path in this function, so I am removing it completely, and checking to make sure that a graph is uploaded to the robot before this function attempts to navigate.

2023-06-29 19:38 UTC, Rhettoric74 commented on spot_driver/scripts/examples/mapping_example.py
> +        # waypoint arguments must be passed in as a list.
I just changed it so that you can pass in either a single waypoint or a list, in which case it will use the first waypoint in the list.

2023-06-29 19:40 UTC, Rhettoric74 commented on spot_driver/scripts/examples/mapping_example.py
> +        time.sleep(2)
removed!

2023-07-05 18:37 UTC, amit-manicka commented on spot_driver/src/spot_driver/spot_wrapper.py
> +    ############################################################################
I think it would make sense to move the code to a separate class as all of it has a similar idea of recording maps. I'll get to that when I'm in lab

2023-07-05 18:38 UTC, amit-manicka commented on spot_driver/src/spot_driver/spot_wrapper.py
> +#################### Added code ######################
Understood, I only used those comments as a form of debug as it was easy to lose where I added things in the core code

2023-07-05 18:40 UTC, amit-manicka commented on spot_driver/scripts/examples/recording_example.py
> +    def __upload_recording_test__(self, uploadPath): #Test Script for testing an upload of a pre-recorded graph
Understood. I only did that as that was my coding style, but I can fix it to match docstring notation

2023-07-05 18:42 UTC, amit-manicka commented on spot_driver/src/spot_driver/spot_wrapper.py
> +# Additional import statements for recording
understood, I'll get right on it when I'm in lab

2023-07-05 18:45 UTC, amit-manicka commented on spot_driver/scripts/examples/recording_example.py
> +    def __obtain_recording_test__(self): #Test script for recording a path and downloading the recording to local machine
I think this function is part of a file it was copied over from for template purposes. I originally left it in on the fear that deleting it may break something elsewhere, but I am more than happy to remove it.

2023-07-10 17:38 UTC, baldeeb requested changes
There seem to be quite a few issues that are not addressed.

Allow me to resolve my comments for the time being and add comments to indicate that you addressed them. 

Make sure you are committing your fixes to the same branch!

2023-07-10 17:38 UTC, baldeeb commented on spot_driver/scripts/examples/mapping_example.py
> +        self.spot = SpotWrapper('admin',
I know this was just following other examples but I think we should try and fix all. 

when we run spot's setup.sh BOSDYN_CLIENT_PASSWORD, BOSDYN_CLIENT_USERNAME, SPOT_IP are set with the info you want. use the os library to access this information as such:
```
import os
os.getenv('PATH')
```

2023-07-10 17:38 UTC, baldeeb commented on spot_driver/scripts/examples/recording_example.py
> +        self.spot = SpotWrapper('admin',
Yess check the comment in the mapping example.

2023-07-10 17:38 UTC, baldeeb commented on spot_driver/scripts/examples/mapping_example.py
> +        # waypoint arguments must be passed in as a list.
Please let me resolve my comments so I can more easily track what was done. 

I can't see the update in this merge request. Can you make sure that all such updates are merged together?

2023-07-10 20:06 UTC, amit-manicka commented on spot_driver/src/spot_driver/spot_wrapper.py
> +    ############################################################################
Fixed, check the utils folder for the graphNav_wrapper.py file

2023-07-10 20:07 UTC, amit-manicka commented on spot_driver/src/spot_driver/spot_wrapper.py
> +#################### Added code ######################
Fixed, removed these comments as I relocated the bulk of the code to the graphNav_wrapper.py file

2023-07-10 20:07 UTC, amit-manicka commented on spot_driver/src/spot_driver/spot_wrapper.py
> +# Additional import statements for recording
Fixed, removed these comments as I relocated the bulk of the code to the graphNav_wrapper.py file

2023-07-10 20:07 UTC, amit-manicka commented on spot_driver/scripts/examples/recording_example.py
> +    #########################################################################################
Fixed, removed these comments as I relocated the bulk of the code to the graphNav_wrapper.py file

2023-07-10 20:07 UTC, amit-manicka commented on spot_driver/scripts/examples/recording_example.py
> +    def __obtain_recording_test__(self): #Test script for recording a path and downloading the recording to local machine
Fixed, deleted the extra function

2023-07-10 20:08 UTC, amit-manicka commented on spot_driver/scripts/examples/mapping_example.py
> +        self.spot = SpotWrapper('admin',
Fixed, and left a comment about how to declare environment variables too

2023-07-11 16:15 UTC, amit-manicka commented on spot_driver/scripts/examples/recording_example.py
> +        self.spot = SpotWrapper('admin',
They've been rewritten now

2023-08-28 19:05 UTC, baldeeb approved these changes

2023-08-28 19:07 UTC, merged