Work/chair grasp - Added additional grasp point, rviz now shows tag tracking status
RPM-lab-UMN/spot_ros pull request #3
Opened 2023-06-27 18:38 UTC by ryan-roche

- Added framework for multiple chair grasp points
- Added "backrest right side", renamed original grasp point to "backrest left side"
- Added tickbox to "toggle tag tracking" button to surface tag pose subscription status in rviz

2023-07-10 18:48 UTC, baldeeb requested changes
Added some comments! Cool added functions. Let's make the code clean by removing unused code and redundant code.

2023-07-10 18:48 UTC, baldeeb commented on spot_driver/src/spot_driver/utils/ros_wrappers/gripper_action.py
> +        rospy.loginfo(goal)
Make the log more indicative of that things are not yet implemented here. 
Also, log as warning.

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +            R (list): the rotation of the grasp relative to the marker orientation.'''
This comment does not seem to match the server called. the class prompts the tracectoy action not the grasp action.

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
>          rospy.loginfo(result)
what is the difference between this class and the GoToMarkerCallback class with the proper t and R passed in?

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +    def __init__(self, server_name, grasp_pos, t=[0.2, 0.0, 0.5], R=[0, 0, 0]):
why add a grasp_pos instead of t, and R?

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +        self._grasp_pos['R'] = self._R
The grasp pose is updated with every iteration using constant values, why?

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +    def __init__(self, server_name, grasp_pos, t=[0.0, 0.0, 0.0], R=[0, 0, 0]):
Similar as the comments above. I don't understand the addition of the grasp pose variable

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/chair_marker
> +    grasps = [
Use a more descriptive name or add a comment. Grasps relative to chair pose?

Also, can you include all the poses that were specified in the above dictionary and remove any grasp info from the above dictionary?

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/chair_marker
> +    def toggle_tag_tracking_callback(feedback):
It would be nice to make this more general if time permits. 

If you decide to do so, make it a functor (a class where the call function houses this functionality). Pass the server and some list of callbacks (like the update_marker_sub.toggle) as part of the initialization. Then pass an instance of said class to the callback.

Let me know if you decide to take this on or not.

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/chair_marker
> +        rospy.loginfo("Toggle pose topic subscription")
Can we remove the rospy.loginfo from this function? They seem quite trivial.

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/chair_marker
> +                                      GoToRightMarkerCallback,
I don't see this used anywhere. If unused please remove.

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/chair_marker
> +    for grasp in grasps:
noice! :+1:

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/chair_marker
> +                                           callback=MultiGraspToggleCallback(
@ryan-roche As discussed it would be nice to make a toggle wrapper that can generalize this functionality. That way we can remove the function that toggles the tracking.

Let me know if this seems trivial enough and if you take it on.

2023-07-10 18:48 UTC, baldeeb commented on spot_viz/scripts/chair_marker
> +
I don't like that this is tracked in this file. This should be part of the grasp callback functor. 

I realize that now that there are multiple possible grasps we will need to specify different drag actions. Have the drag callback functor expose the ability to set its R, and t offsets. The multi-grasp callback can then trigger the drag and let it know where the grasp is!

Thoughts??\

2023-07-11 17:17 UTC, ryan-roche commented on spot_driver/src/spot_driver/utils/ros_wrappers/gripper_action.py
> +        rospy.loginfo(goal)
The functionality on the side of the `MultiGraspActionServer` object has been completed. A similar "not-yet-implemented" warning message has been added to the task wrapper in a future commit

2023-07-11 17:19 UTC, ryan-roche commented on spot_viz/scripts/chair_marker
> +                                      GoToRightMarkerCallback,
Done.

2023-07-11 17:38 UTC, ryan-roche reviewed
I went through and addressed the comments pertaining to my code, and left a note on the code that was added by others.

2023-07-11 17:38 UTC, ryan-roche commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +            R (list): the rotation of the grasp relative to the marker orientation.'''
@revanthsenthil

2023-07-11 17:38 UTC, ryan-roche commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +            R (list): the rotation of the grasp relative to the marker orientation.'''
It looks like this code was added by you after I made the PR on this branch. Could you take a look at this? @revanthsenthil

2023-07-11 17:38 UTC, ryan-roche commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
>          rospy.loginfo(result)
@revanthsenthil Same for this - looks like you pushed changes to me and Ben's branch after we made the PR (could have been from when you were using the laptop). Could you look at & resolve this comment?

2023-07-11 17:38 UTC, ryan-roche commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +    def __init__(self, server_name, grasp_pos, t=[0.2, 0.0, 0.5], R=[0, 0, 0]):
@BenMan95

2023-07-11 17:38 UTC, ryan-roche commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +        self._grasp_pos['R'] = self._R
@BenMan95

2023-07-11 17:38 UTC, ryan-roche commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +    def __init__(self, server_name, grasp_pos, t=[0.0, 0.0, 0.0], R=[0, 0, 0]):
@BenMan95

2023-07-11 18:42 UTC, revanthsenthil commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
>          rospy.loginfo(result)
@ryan-roche You can delete all instances of GoToRightMarkerCallback

2023-08-24 15:46 UTC, baldeeb commented
Cool but a lot is still happening on this branch. Also Ben and Revanth don't seem to be responding. @ryan-roche Can you make changes or arguments based on the comments I left?
For example: 
 - revanth's class is not used so simply delete it.
 - Ben's added parameters (passing pose separately) are hard to justify so either ask him personally or remove them.
 
 Sorry this is more work but I am hoping we also get things merged before you guys have to go. 
 
 One last note. Although this commit mentions a few updates it has some helper functions relating to the local grid. Is that intentional? If Ben is just using this branch, maybe branch off wherever you see fit and submit a merge request again.

2023-08-24 15:55 UTC, ryan-roche commented
> Cool but a lot is still happening on this branch. Also Ben and Revanth don't seem to be responding. @ryan-roche Can you make changes or arguments based on the comments I left?
> 
> For example: 
> 
>  - revanth's class is not used so simply delete it.
> 
>  - Ben's added parameters (passing pose separately) are hard to justify so either ask him personally or remove them.
> 
>  
> 
>  Sorry this is more work but I am hoping we also get things merged before you guys have to go. 
> 
>  
> 
>  One last note. Although this commit mentions a few updates it has some helper functions relating to the local grid. Is that intentional? If Ben is just using this branch, maybe branch off wherever you see fit and submit a merge request again. 

I know that Ben used the local grid for the grasp-selection part of multigrasp, but that functionality should all be within 'gripper-action.py'. My hunch is that those references are vestigial from a previous attempt at implementing the grasp-selection, but I'm not sure. I'll try to get ahold of him.

2023-08-24 16:06 UTC, BenMan95 commented
I implemented the grasp-selection logic for the multigrasp in `spot_task_wrapper.py`. The local grid helper functions you mentioned are some functions I added to `ros_helpers.py` to make it easier to read individual values from the local grid.

2023-08-24 16:22 UTC, BenMan95 commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +        self._grasp_pos['R'] = self._R
`DragToMarkerCallback` needs to know the current grab position in order to drag the chair accurately. `grasp_pos` is a dictionary which `MultiGraspActionCallback` stores the grasp position in after the multigrasp is performed. Then `DragToMarkerCallback` is able to read the current grasp position from that dictionary.

2023-08-24 16:26 UTC, BenMan95 commented on spot_viz/scripts/interactive_marker_utils/callbacks.py
> +    def __init__(self, server_name, grasp_pos, t=[0.0, 0.0, 0.0], R=[0, 0, 0]):
`grasp_pos` is a dictionary passed to the multigrasp callback so that it can save the selected grasp position when called. The dragging callback can then read from that dictionary to check the current grasp position.

2024-06-26 19:01 UTC, merged